// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1gVvIDs3gq_GAad2zvQkur08vg_H82eQ',
    appId: '1:374168508442:web:35de541cd1c58aa05799a3',
    messagingSenderId: '374168508442',
    projectId: 'wayfarer-ai-c9901',
    authDomain: 'wayfarer-ai-c9901.firebaseapp.com',
    storageBucket: 'wayfarer-ai-c9901.firebasestorage.app',
    measurementId: 'G-E3F1RW9YH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1gVvIDs3gq_GAad2zvQkur08vg_H82eQ',
    appId: '1:374168508442:android:PLACEHOLDER',
    messagingSenderId: '374168508442',
    projectId: 'wayfarer-ai-c9901',
    storageBucket: 'wayfarer-ai-c9901.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1gVvIDs3gq_GAad2zvQkur08vg_H82eQ',
    appId: '1:374168508442:ios:PLACEHOLDER',
    messagingSenderId: '374168508442',
    projectId: 'wayfarer-ai-c9901',
    storageBucket: 'wayfarer-ai-c9901.firebasestorage.app',
    iosBundleId: 'com.wayfarer.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1gVvIDs3gq_GAad2zvQkur08vg_H82eQ',
    appId: '1:374168508442:ios:PLACEHOLDER',
    messagingSenderId: '374168508442',
    projectId: 'wayfarer-ai-c9901',
    storageBucket: 'wayfarer-ai-c9901.firebasestorage.app',
    iosBundleId: 'com.wayfarer.ai',
  );
}






